export const S = {
  loading: { display:'flex', alignItems:'center', justifyContent:'center', height:'100vh', fontFamily:'Georgia, serif', color:'#6b7280', flexDirection:'column', gap:12 },
  page: { maxWidth:560, margin:'0 auto', padding:'24px 16px 100px', fontFamily:"'Georgia', serif", color:'#1f2937', minHeight:'100vh', background:'#fafaf8' },
  hero: { textAlign:'center', padding:'32px 0 24px' },
  heroIcon: { fontSize:48, marginBottom:8 },
  heroTitle: { fontSize:32, fontWeight:700, margin:0, letterSpacing:-1, color:'#111' },
  heroSub: { fontSize:15, color:'#6b7280', marginTop:6 },
  card: { background:'#fff', borderRadius:16, padding:24, boxShadow:'0 1px 4px rgba(0,0,0,0.08)', border:'1px solid #e5e7eb' },
  cardTitle: { fontSize:20, fontWeight:700, margin:'0 0 4px', color:'#111' },
  subtitle: { color:'#6b7280', fontSize:14, margin:'0 0 8px' },
  label: { display:'block', fontSize:13, fontWeight:600, color:'#374151', marginBottom:4, marginTop:12 },
  labelNote: { color:'#9ca3af', fontWeight:400, fontSize:12 },
  input: { width:'100%', padding:'10px 12px', borderRadius:8, border:'1px solid #d1d5db', fontSize:15, boxSizing:'border-box', fontFamily:'inherit', outline:'none', background:'#fafafa' },
  btn: { padding:'11px 20px', borderRadius:10, background:'#111', color:'#fff', fontSize:14, fontWeight:600, border:'none', cursor:'pointer', marginTop:12, fontFamily:'inherit' },
  btnFull: { width:'100%', padding:'12px', borderRadius:10, background:'#111', color:'#fff', fontSize:15, fontWeight:600, border:'none', cursor:'pointer', marginTop:12, fontFamily:'inherit' },
  btnSecondary: { width:'100%', padding:'11px', borderRadius:10, background:'transparent', color:'#111', fontSize:15, fontWeight:600, border:'2px solid #111', cursor:'pointer', fontFamily:'inherit', marginTop:10 },
  btnGhost: { width:'100%', padding:'10px', borderRadius:10, background:'transparent', color:'#9ca3af', fontSize:14, border:'none', cursor:'pointer', fontFamily:'inherit' },
  error: { color:'#ef4444', fontSize:13, margin:'6px 0 0' },
  pollBadge: { display:'inline-block', background:'#dcfce7', color:'#166534', fontSize:11, fontWeight:700, padding:'2px 8px', borderRadius:99, letterSpacing:0.5 },
  closedBadge: { display:'inline-block', background:'#fee2e2', color:'#991b1b', fontSize:11, fontWeight:700, padding:'2px 8px', borderRadius:99 },
  respCount: { fontSize:13, color:'#9ca3af', margin:'0 0 12px' },
  shareBox: { background:'#f9fafb', borderRadius:10, padding:'10px 12px', marginBottom:4, marginTop:8 },
  shareLabel: { fontSize:11, fontWeight:700, color:'#6b7280', display:'block', marginBottom:6 },
  shareRow: { display:'flex', alignItems:'center', gap:8 },
  shareUrl: { fontSize:11, color:'#374151', flex:1, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontFamily:'monospace' },
  copyBtn: { padding:'4px 10px', borderRadius:6, background:'#111', color:'#fff', fontSize:12, fontWeight:600, border:'none', cursor:'pointer', fontFamily:'inherit', flexShrink:0 },
  copyBtnDone: { padding:'4px 10px', borderRadius:6, background:'#4ade80', color:'#fff', fontSize:12, fontWeight:600, border:'none', cursor:'pointer', fontFamily:'inherit', flexShrink:0 },
  closedNote: { background:'#fee2e2', color:'#991b1b', borderRadius:8, padding:'10px 12px', fontSize:13, fontWeight:600, marginTop:12, textAlign:'center' },

  fillHeader: { display:'flex', alignItems:'flex-start', gap:12, marginBottom:16 },
  fillTitle: { fontSize:20, fontWeight:700, margin:0, color:'#111' },
  fillSub: { fontSize:13, color:'#6b7280', margin:'2px 0 0' },
  backBtn: { background:'none', border:'none', cursor:'pointer', fontSize:14, color:'#6b7280', padding:'4px 0', whiteSpace:'nowrap', fontFamily:'inherit' },
  legend: { display:'flex', gap:10, marginBottom:16, flexWrap:'wrap' },
  legendItem: { display:'flex', alignItems:'center', gap:5, fontSize:12, color:'#6b7280' },
  legendDot: { width:10, height:10, borderRadius:99, display:'inline-block' },
  monthBlock: { marginBottom:24 },
  monthLabel: { fontSize:13, fontWeight:700, color:'#9ca3af', letterSpacing:1, textTransform:'uppercase', margin:'0 0 10px' },

  saveBar: { position:'fixed', bottom:0, left:0, right:0, background:'#fff', borderTop:'1px solid #e5e7eb', padding:'12px 16px', display:'flex', alignItems:'center', justifyContent:'space-between', gap:10, zIndex:10 },
  btnTrash: { padding:'10px 14px', borderRadius:10, background:'transparent', color:'#ef4444', fontSize:13, fontWeight:600, border:'1px solid #fca5a5', cursor:'pointer', fontFamily:'inherit' },
  btnSmallDanger: { padding:'8px 12px', borderRadius:8, background:'#ef4444', color:'#fff', fontSize:13, fontWeight:600, border:'none', cursor:'pointer', fontFamily:'inherit', whiteSpace:'nowrap' },
  btnSmallGhost: { padding:'8px 12px', borderRadius:8, background:'transparent', color:'#6b7280', fontSize:13, border:'1px solid #d1d5db', cursor:'pointer', fontFamily:'inherit' },

  lockBtn: { padding:'6px 12px', borderRadius:8, background:'transparent', color:'#374151', fontSize:12, fontWeight:600, border:'1px solid #d1d5db', cursor:'pointer', fontFamily:'inherit', whiteSpace:'nowrap' },
  unlockBtn: { padding:'6px 12px', borderRadius:8, background:'#fee2e2', color:'#991b1b', fontSize:12, fontWeight:600, border:'1px solid #fca5a5', cursor:'pointer', fontFamily:'inherit', whiteSpace:'nowrap' },
  closedBanner: { background:'#fee2e2', color:'#991b1b', borderRadius:10, padding:'10px 14px', fontSize:13, fontWeight:600, marginBottom:16 },

  perfectBanner: { background:'#f0fdf4', border:'1px solid #bbf7d0', borderRadius:12, padding:16, marginBottom:16 },
  perfectTitle: { fontWeight:700, fontSize:15, color:'#166534', marginBottom:8 },
  perfectList: { display:'flex', flexWrap:'wrap', gap:6 },
  perfectChip: { background:'#dcfce7', color:'#166534', fontSize:12, fontWeight:600, padding:'4px 10px', borderRadius:99 },
  bestBanner: { background:'#fffbeb', border:'1px solid #fde68a', borderRadius:12, padding:16, marginBottom:16 },
  bestTitle: { fontWeight:700, fontSize:15, color:'#92400e', marginBottom:8 },
  bestChip: { background:'#fef3c7', color:'#92400e', fontSize:12, fontWeight:600, padding:'4px 10px', borderRadius:99 },

  orgWeekend: { borderRadius:10, padding:'12px 14px', marginBottom:10, border:'1px solid #e5e7eb' },
  orgWeekendHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:8 },
  orgWeekendDate: { fontSize:14, fontWeight:700, color:'#111', display:'flex', alignItems:'center', gap:8, flexWrap:'wrap' },
  freeTag: { background:'#4ade80', color:'#fff', fontSize:11, fontWeight:700, padding:'2px 7px', borderRadius:99 },
  bestTag: { background:'#fbbf24', color:'#fff', fontSize:11, fontWeight:700, padding:'2px 7px', borderRadius:99 },
  orgCount: { fontSize:12, color:'#6b7280', display:'flex', alignItems:'center', gap:4 },
  personGrid: { display:'flex', flexDirection:'column', gap:5 },
  personRow: { display:'flex', alignItems:'center', gap:8 },
  personName: { fontSize:13, color:'#374151', minWidth:80, flex:1 },
  personStatus: { width:14, height:14, borderRadius:3, display:'inline-block' },
  personLabel: { fontSize:11, color:'#9ca3af', minWidth:50 },
  emptyState: { textAlign:'center', padding:'48px 24px', color:'#6b7280' },

  realtimeDot: { width:7, height:7, borderRadius:99, background:'#4ade80', display:'inline-block', marginRight:5, animation:'pulse 2s infinite' },
}
